spring:     
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://192.168.0.114:3306/semes_db
    username: root
    password: password

  jpa:
    hibernate:
      ddl-auto: update
      
server:
    port: 8000