spring:
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://192.168.0.114:3306/semes_db
    username: root
    password: password
    
# 
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false

  jpa:
    hibernate:
      ddl-auto: update #create update none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true 
  mail:
    host: smtp.gmail.com
    port: 587
    username: mnew2m@gmail.com
    password: lmcswuquibcnsvjf
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true 
      
#logging:
#  level:
#    org:
#      hibernate:  
#        type:
#          descriptor:
#            sql: trace 
      
server:
    port: 8000