spring:

  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://192.168.0.114:3306/audib
#    url: jdbc:mariadb://localhost:3306/ysy_db
    username: root
    password: password
#    password: 1234

  servlet:
    multipart:
      maxFileSize: 10MB
      maxRequestSize: 20MB

  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
     
    #deserialization:
      #fail-on-unknown-properties: true #json->Object 변환 시 unknowon 오류 무시      

  jpa:
    hibernate:
      ddl-auto: update #create update none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true 
  mail:
    host: smtp.gmail.com
    port: 587
    username: mnew2m@gmail.com
    password: lmcswuquibcnsvjf
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true 
      
#logging:
#  level:
#    org:
#      hibernate:  
#        type:
#          descriptor:
#            sql: trace 
      
server:
    port: 8000