#configuration
#spring.jpa.hibernate.ddl-auto=update
#spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
#spring.datasource.url=jdbc:mysql://192.168.0.114:3306/mc_cost
#spring.datasource.url=jdbc:mariadb://192.168.0.114:3306/semes_db
#spring.datasource.username=root
#spring.datasource.password=password


spring:     
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://192.168.0.114:3306/semes_db
    username: root
    password: password

server:
  port: 8000

jpa:
    hibernate:
      ddl-auto: update