spring:     
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://192.168.0.114:3306/semes_db
    username: root
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
      
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
      
server:
    port: 8000